fix: no auth on /token with PKCE
worldcoin/developer-portal pull request #383
Opened 2023-09-18 15:50 UTC by 0xPenryn

2023-11-09 01:33 UTC, pdtfh requested changes
@0xPenryn let's do this slightly different to maintain security. we will allow devs to configure their app as public in the Dev Portal (similar to how [Auth0 does it](https://auth0.com/docs/get-started/applications/confidential-and-public-applications/view-application-type)).

if the client is public, we enforce PKCE.
if the client is confidential, we enforce authentication (and PKCE when applicable)

2023-11-09 01:33 UTC, pdtfh commented on web/src/pages/api/v1/oidc/openid-configuration.ts
> +    token_endpoint_auth_methods_supported: [
I think this is missing `none` because we'll support public clients

2023-11-09 01:33 UTC, pdtfh commented on web/tests/integration/oidc/token.test.ts
> +    // #region -> Can get app_id using auth token without passing it directly
this should be a different test case, and naming should be around using client_secret_post

2023-11-09 01:33 UTC, pdtfh commented on web/tests/integration/oidc/token.test.ts
> +  test("Can get app_id using auth token", async () => {
```suggestion
  test("can get token using auth code with client_secret_basic auth", async () => {
```

2023-11-09 01:33 UTC, pdtfh commented on web/tests/integration/oidc/token.test.ts
> +    // #region -> Can get app_id with code_verifier & client_id
should be a different test case, and naming around public client support

2024-06-06 01:06 UTC, andy-t-wang commented
@0xPenryn Close this?

2024-06-07 14:13 UTC, closed without merging